///////////////////////////////////////////////////////////
//  User_Application.cs
//  Implementation of the Class User_Application
//  Generated by Enterprise Architect
//  Created on:      01-f¨¦vrier.-2015 15:45:19
//  Original author: Callot Antoine
///////////////////////////////////////////////////////////
using System; 
using System.Net;
using System.Net.NetworkInformation;
using System.Net.Sockets;
using System.Text;

public class User_Application {
	string ip_server;
	int Port; 
	Socket Sock; 

	public User_Application(string ip,int port){
		ip_server = ip;
		Port = port; 

	}

	~User_Application(){

	}

	public int Actualiser(){

		return 0;
	}

	public char[] DemandeCasier(){
		//buffer de numero de casier :
		Byte[] numero_casier  = new byte[2];
		Byte[] demande_reservation = new byte[1];

		//Place la valeur "d" pour demander la Reservation
		demande_reservation = Encoding.ASCII.GetBytes("d"); 

		connection ();

		//demande de reservation : 
		Sock.Send (demande_reservation,demande_reservation.Length,0);

		//reception numero : 
		Sock.Receive (numero_casier);
	
		//convertie byte en char[]
		char[] envoi = System.Text.Encoding.ASCII.GetString(numero_casier).ToCharArray(); 
		return envoi;
	}

	public char[] recuperation_mdp(){
		//buffer de mots de passe : 
		Byte[] mots_de_passe  = new byte[4];

		//demande de mot de passe : 
		Byte[] demande_mdp = new byte[1];
		demande_mdp = Encoding.ASCII.GetBytes("v");//en envoyant un v pour la validation 
		Sock.Send (demande_mdp, demande_mdp.Length, 0); 

		//Reception de mots de passe
		Sock.Receive (mots_de_passe, mots_de_passe.Length, 0); 

		//convertie byte en char[]
		char[] envoi = System.Text.Encoding.ASCII.GetString(mots_de_passe).ToCharArray(); 
		return envoi;
	
	}



	public char[] ValidationCasier(){

		return null;
	}

	public void connection(){
		Sock = null;
		IPHostEntry hostEntry = null;
		 

		// recup¨¦re les information de l'h?te
		hostEntry = Dns.GetHostEntry(ip_server);

		// Boucle ¨¤ travers le AddressList pour obtenir le AddressFamily, pour ¨¦viter
		// Une exception qui se produit lorsque l'adresse IP de l'hote ne est pas compatible avec la famille d'adresse
		// (Typique dans le cas IPv6).
		foreach(IPAddress address in hostEntry.AddressList)
		{
			IPEndPoint ipe = new IPEndPoint(address,Port);
			Socket tempSocket = 
				new Socket(ipe.AddressFamily, SocketType.Stream, ProtocolType.Tcp);


			tempSocket.Connect(ipe);


			if(tempSocket.Connected)
			{
				Sock = tempSocket;
				break;
			}
			else
			{
				continue;
			}
		}


	}

}
